### ISSUE TITLE
Try MsgModify with invalid tokenIndex, does not blocking.

### ISSUE THREAD

**Issue by hyenjong-yoo** [Finschia/finschia-sdk#1101]
## Summary of Bug

lbm.collection.v1.MsgModify
AS-IS :  Request MsgModify to Invalid TokenIndex with valid NFT TokenIndex, but response not correct event type_name's value <lbm.collection.v1.FTClass>

```
request ex) MsgModify.fromPartial({
    "contractId": "contractId",
    "owner": "owner",
    "tokenType": "10000001",
    "tokenIndex": "00000000",
    "changes": "changes"
})
```
```
response ex)
{
    "events":
    [
        {
            "type": "lbm.collection.v1.EventModifiedTokenClass",
            "attributes":
            [
                {
                    "key": "changes",
                    "value": "[{key:name,value:nFrameworkFT2}]"
                },
                {
                    "key": "contract_id",
                    "value": "3ee3e2f6"
                },
                {
                    "key": "operator",
                    "value": "tlink1fpgj0gg6w4f2f642qsrkgrswj9jdmeer8s9ffx"
                },
                {
                    "key": "token_type",
                    "value": "10000001"
                },
                {
                    "key": "type_name",
                    "value": "lbm.collection.v1.FTClass"
                }
            ]
        },
        {
            "type": "message",
            "attributes":
            [
                {
                    "key": "action",
                    "value": "/lbm.collection.v1.MsgModify"
                }
            ]
        }
    ]
}
```
TO-BE :
Blocking Invalid NFT Token Index MsgModify

## Version
v0.47.1-rc2
v0.47.3-0.20230817110929-1df6411c6429

## Steps to Reproduce

0. Create Collection and Issue NFT token and Mint NFT
1. Make MsgModify with tokenType = 10000001, tokenIndex=00000000
2. Send Tx and Check Tx Response
____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by 0Tech** [comment]
Thank you for the report. The chain must reject the request, including a tokentype of nft class and token index of "00000000". The specification would be of daphne, hence the current implementation is not compatible with the old spec.

**Comment by 0Tech** [comment]
The linked PR should have fixed the bug. You may reopen this issue if you come up with any relevant problem. Thank you @hyenjong-yoo.
