### ISSUE TITLE
Make x/wasm's API costs and event gas costs into parameters

### ISSUE THREAD

**Issue by loloicci** [Finschia/finschia-sdk#414]
## Summary
API costs of x/wasm are const now. And, event gas costs are stored in keeper. Make them into parameters.

## Problem Definition
https://github.com/line/lbm-sdk/blob/dba5a4553fcf128f11abe5fcb7d9a551915c1e82/x/wasm/keeper/api.go#L15 and https://github.com/line/lbm-sdk/blob/dba5a4553fcf128f11abe5fcb7d9a551915c1e82/x/wasm/keeper/api.go#L26 define API costs (5 and 4). In the original wasmd, these are made into options https://github.com/CosmWasm/wasmd/pull/533.
Other values than API costs that are made into options are already parameters in our x/wasm module.

And, event gas costs are defined in https://github.com/CosmWasm/wasmd/pull/539.

## Proposal

Make API costs into parameters.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by loloicci** [comment]
refer also: https://github.com/CosmWasm/wasmd/pull/539

**Comment by 170210** [comment]
This issue has been resolved in [x/wasm/keeper/api.go](https://github.com/zemyblue/wasmd/blob/db131c5cfc16c8aa1872ff82116ab2e7a2058c1e/x/wasm/keeper/api.go)
