### ISSUE TITLE
Support hardware ledger

### ISSUE THREAD

**Issue by zemyblue** [Finschia/finschia-sdk#464]
## Summary

Need to be support hardware ledger

## Proposal

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by tkxkd0159** [comment]
Our ledger app is not deployed yet([ref](https://github.com/Finschia/ledger-finschia)). But we can use ledger with Cosmos Ledger App (Coin Type 118)
