### ISSUE TITLE
Version v0.46.0-rc5 is incorrectly shown as rc2

### ISSUE THREAD

**Issue by torao** [Finschia/finschia-sdk#606]
## Summary of Bug

I checked out and built a commit 1bc3aac98, which is tagged v0.46.0-rc5, then I got the version notation  v0.46.0-rc2. 

```
% simd version
0.46.0-rc2-178-g1bc3aac98
```

It should correctly say `v0.46.0-rc5-XXX-g1bc3aac98`.

## Version

v0.46.0-rc5 (1bc3aac98)

## Steps to Reproduce

The following operation shows that v0.46.0-rc5 is checked out but the version number is replaced by v0.46.0-rc2 by `make`.

```
% git checkout v0.46.0-rc5

% make install
.. -X github.com/line/lbm-sdk/version.Version=0.46.0-rc2-178-g1bc3aac98 ..

% simd version
0.46.0-rc2-178-g1bc3aac98
```

The version number is obtained using `git describe` in [Makefile#5](https://github.com/line/lbm-sdk/blob/v0.46.0-rc5/Makefile#L5). However, it seems to reference the v0.46.0-rc2 tag, even though the most recent tag is v0.46.0-rc5.

```
% git describe
v0.46.0-rc2-178-g1bc3aac98

% git describe --tag
v0.46.0-rc5

% git log --oneline
1bc3aac98 (HEAD -> v0.46.0-rc5, tag: v0.46.0-rc5, upstream/main) Remove prefetch functionality (#596)
c0ce87f0a feat: change amino codec path from `lbm-sdk/` to `cosmos-sdk/` (#600)
d4a8be2bc chore(deps): Bump github.com/spf13/cobra from 1.4.0 to 1.5.0 (#569)
...
```

____

## For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by zemyblue** [comment]
This is not a problem for now.
