### ISSUE TITLE
Make CheckTendermintError to handle ErrTxInMap

### ISSUE THREAD

**Issue by zbvs** [Finschia/finschia-sdk#697]
## Summary

CheckTendermintError also needs to handle `ErrTxInMap` with correspond { Codespace, Code-Number }, as many GRPC clients want to check  TxHash duplication or sequence number duplication error 

## Problem Definition

Currently, CheckTendermintError doesn't handle `ErrTxInMap` error ( https://github.com/line/lbm-sdk/blob/main/client/broadcast.go#L59 ),  
which occurs when Tx is in mempool and not confirmed yet. ( https://github.com/line/ostracon/blob/main/mempool/clist_mempool.go#L302 ).

As many grpc clients want to check sequence number duplication with { Codespace, Code-Number }, it needs to handle `ErrTxInMap` for GRPC clients, so that it can return { Codespace, Code-Number }

## Proposal

Make CheckTendermintError to handle ErrTxInMap
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by tkxkd0159** [comment]
We will discard duplicate Tx in the future. ([ref](https://github.com/cometbft/cometbft/blob/v0.34.29/mempool/v0/clist_mempool.go#L395-L406))
