### ISSUE TITLE
A script that documents the error code of each module is required

### ISSUE THREAD

**Issue by zemyblue** [Finschia/finschia-sdk#905]
## Summary

* Add a script that documents the error code of each module.

## Problem Definition

It is not easy the client developer of chain are looking for the each error code and message. So I think it's better to make a script that documents a error codes and messages of each module, like protobuf's MD file.

## Proposal

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by tkxkd0159** [comment]
Duplicate issue
#942
