### ISSUE TITLE
Correct the description directly below unreleased in CHANGELOG.md.

### ISSUE THREAD

**Issue by kokeshiM0chi** [Finschia/finschia-sdk#950]
## Summary

PRs under unreleased in `CHANGELOG.md` should be placed in the h3 hierarchy.

## Problem Definition

Currently, the `CHANGELOG.md` is not organized.
PRs directly under unreleased should be classified as features, improvements, etc. in the h3 hierarchy.
However, they are not classified correctly. Therefore, it needs to be corrected.

## Proposal

PRs directly under unreleased should be written in the appropriate location directly under one of the following. :features,improvements, bug fixes,....etc
____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [ ] Appropriate contributors tagged (Not decided yet.)
- [ ] Contributor assigned/self-assigned (Not decided yet.)

**Comment by zemyblue** [comment]
Changelog is always updated if the release complete.
And I think this issue is solved by #992 .
